groups:
  - name: carbonio_service_down
    interval: 30s
    rules:
      - alert: ServiceDown1h
        expr: consul_catalog_service_node_healthy{job="consul"} == 0
        for: 1h
        labels:
          severity: blocker
        annotations:
          summary: Consul service healthcheck failed (node {{ $labels.node }})
          description: "Service {{ $labels.service_name }} (ID: {{ $labels.service_id }}) on {{ $labels.node }} has been down for over 1 hour."
      - alert: ServiceDown30m
        expr: consul_catalog_service_node_healthy{job="consul"} == 0
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: Consul service healthcheck failed (node {{ $labels.node }})
          description: "Service {{ $labels.service_name }} (ID: {{ $labels.service_id }}) on {{ $labels.node }} has been down for over 30 minutes."
      - alert: ServiceDown1m
        expr: consul_catalog_service_node_healthy{job="consul"} == 0
        for: 1m
        labels:
          severity: alert
        annotations:
          summary: Consul service healthcheck failed (node {{ $labels.node }})
          description: "Service {{ $labels.service_name }} (ID: {{ $labels.service_id }}) on {{ $labels.node }} has been down for over 1 minute."