groups:
  - name: mail_queue
    interval: 30s
    rules:
      - alert: More_Than_300_Deferred
        expr: postfix_queue_stat{job="node"} >= 300
        for: 2m
        labels:
          severity: blocker
        annotations:
          summary: Mail queue size exceeded 300 messages (instance {{ $labels.instance }})
          description: "Mail queue on {{ $labels.instance }} has {{ $value }} messages pending in the {{ $labels.queue }} queue."
      - alert: More_Than_200_Deferred
        expr: postfix_queue_stat{job="node"} >= 200
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Mail queue size exceeded 200 messages (instance {{ $labels.instance }})
          description: "Mail queue on {{ $labels.instance }} has {{ $value }} messages pending in the {{ $labels.queue }} queue."
      - alert: More_Than_100_Deferred
        expr: postfix_queue_stat{job="node"} >= 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Mail queue size exceeded 100 messages (instance {{ $labels.instance }})
          description: "Mail queue on {{ $labels.instance }} has {{ $value }} messages pending in the {{ $labels.queue }} queue."
