groups:
- name: mta_queue
  interval: 5m
  rules:
  - record: mta_queue:active:30m
    expr: min_over_time(postfix_queue_stat{queue="active"}[30m])
  - alert: ActiveQueue30m
    expr: mta_queue:active:30m > 100
    for: 35m
    labels:
      severity: warning
    annotations:
      summary: 'Postfix active queue is high'
      description: 'Warning: More than 100 messages in MTA queue on {{ $labels.instance }}'
  - record: mta_queue:hold:30m
    expr: min_over_time(postfix_queue_stat{queue="hold"}[30m])
  - alert: HoldQueue30m
    expr: mta_queue:hold:30m > 20
    for: 35m
    labels:
      severity: warning
    annotations:
      summary: 'Postfix hold queue is high'
      description: 'Warning: More than 20 messages in MTA queue on hold on {{ $labels.instance }}'
  - record: mta_queue:deferred:30m
    expr: min_over_time(postfix_queue_stat{queue="deferred"}[30m])
  - alert: DeferredQueue30m
    expr: mta_queue:deferred:30m > 50
    for: 35m
    labels:
      severity: warning
    annotations:
      summary: 'Postfix deferred queue is high'
      description: 'Warning: More than 50 deferred messages in MTA queue on {{ $labels.instance }}'