route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
      - severity=~"critical|warning"
      receiver: telegram
      continue: true
    - match:
        job: clamav
      receiver: email
      
receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: BOT_TOKEN
      api_url: https://api.telegram.org
      chat_id: CHAT_ID
      message: '{{ template "telegram.message" . }}'
      parse_mode: "HTML"
  - name: 'email'
    email_configs:
    - to: 'TO_EMAIL'
      from: 'FROM_EMAIL'
      smarthost: SMTP_HOST:PORT
      auth_username: 'USERNAME'
      auth_password: 'PASSWORD'
      require_tls: yes
      
templates:
  - "/etc/carbonio/carbonio-prometheus-alertmanager/templates/*.tmpl"