{
 "title": "Mailstore Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Mailbox",
    "query": {
     "query": "label_values(mailboxd_mbox_get_count, instance)"
    }
   },
   { "name": "MinReqNum", "query": "${VAR_MINREQNUM}" },
   { "name": "ProcTime", "query": "${VAR_PROCTIME}" }
  ]
 },
 "panels": [
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DB connections from the pool",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mailboxd_db_conn_count{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Messages added to a mailbox",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mailboxd_mbox_add_msg_count{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Major GC count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mailboxd_gc_major_count{instance=~\"$instance.*\"}[5m])"
    }
   ]
  },
  {
   "title": "MinorGC count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mailboxd_gc_minor_count{instance=~\"$instance.*\"}[5m])"
    }
   ]
  },
  {
   "title": "LDAP directory context",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mailboxd_ldap_dc_count{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Mailbox from the cache",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mailboxd_mbox_get_count{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mailboxd_soap_ms_avg{instance=~\"$instance.*\"}\n",
     "legendFormat": "SOAP"
    },
    {
     "expr": "mailboxd_pop_ms_avg{instance=~\"$instance.*\"}",
     "legendFormat": "POP"
    },
    {
     "expr": "mailboxd_imap_ms_avg{instance=~\"$instance.*\"}",
     "legendFormat": "IMAP"
    }
   ]
  },
  {
   "title": "Caches size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mailboxd_account_cache_size{instance=~\"$instance.*\"}\n",
     "legendFormat": "LDAP account cache"
    },
    {
     "expr": "mailboxd_cos_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "Cos cache"
    },
    {
     "expr": "mailboxd_domain_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "Domain cache"
    },
    {
     "expr": "mailboxd_fd_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "File Descriptor cache"
    },
    {
     "expr": "mailboxd_mbox_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "Mailboxes cached"
    },
    {
     "expr": "mailboxd_msg_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "Message structures cached"
    },
    {
     "expr": "mailboxd_server_cache_size{instance=~\"$instance.*\"}",
     "legendFormat": "Server cached"
    }
   ]
  },
  { "title": "Protocols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "SOAP Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,soap_exec_count{instance=~\"$instance.*\"} > $MinReqNum) ",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Average processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,soap_exec_ms_avg{instance=~\"$instance.*\"} > $ProcTime) \n",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "IMAP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_imap_count{instance=~\"$instance.*\"}",
     "legendFormat": "IMAP requests received"
    },
    {
     "expr": "mailboxd_imap_conn{instance=~\"$instance.*\"}",
     "legendFormat": "Imap connections"
    },
    {
     "expr": "mailboxd_imap_ssl_conn{instance=~\"$instance.*\"}",
     "legendFormat": "Imap ssl connections"
    }
   ]
  },
  {
   "title": "IMAP Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_imap_threads{instance=~\"$instance.*\"}",
     "legendFormat": "IMAP threads"
    },
    {
     "expr": "mailboxd_imap_ssl_threads{instance=~\"$instance.*\"}",
     "legendFormat": "IMAPs threads"
    }
   ]
  },
  {
   "title": "POP3 Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_pop_count{instance=~\"$instance.*\"}",
     "legendFormat": "POP3 requests"
    },
    {
     "expr": "mailboxd_pop_conn{instance=~\"$instance.*\"}",
     "legendFormat": "POP3 connections"
    },
    {
     "expr": "mailboxd_pop_ssl_conn{instance=~\"$instance.*\"}",
     "legendFormat": "POP3s connections"
    }
   ]
  },
  {
   "title": "POP3 Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_pop_threads{instance=~\"$instance.*\"}",
     "legendFormat": "POP3 threads"
    },
    {
     "expr": "mailboxd_pop_ssl_threads{instance=~\"$instance.*\"}",
     "legendFormat": "POP3s threads"
    }
   ]
  },
  {
   "title": "LMTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_lmtp_conn{instance=~\"$instance.*\"}",
     "legendFormat": "LMTP connections"
    },
    {
     "expr": "mailboxd_lmtp_rcvd_msgs{instance=~\"$instance.*\"}",
     "legendFormat": " Messages received"
    },
    {
     "expr": "mailboxd_lmtp_dlvd_msgs{instance=~\"$instance.*\"}",
     "legendFormat": "Messages delivered"
    },
    {
     "expr": "mailboxd_lmtp_rcvd_rcpt{instance=~\"$instance.*\"}",
     "legendFormat": "LMTP recipients"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$instance.*\", command=\"admin_commands\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"commit\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"delete\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"insert\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"insert_select\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"replace\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"rollback\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"select\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~\"$instance.*\", command=\"update\"}[5m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{instance=~\"$instance.*\"}[4m])"
    }
   ]
  }
 ]
}