{
 "title": "MariaDB",
 "description": "mariadb overview. metrics from mysqld exporter.",
 "tags": [
  "mysql",
  "mariadb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(mysql_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Innodb Data Total Read",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_read{instance=~'$instance.*'}/(1024*1024)"
    }
   ]
  },
  {
   "title": "Innodb Data Total Written",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_innodb_data_written{instance=~'$instance.*'}/(1024*1024)"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_slow_queries{instance=~'$instance.*'}",
     "legendFormat": "Slow Queries on {{instance }}"
    }
   ]
  },
  {
   "title": "Mysql Current Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=~'$instance.*'}"
    }
   ]
  },
  {
   "title": "Mysql Max Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections{instance=~'$instance.*'}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Innodb Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_reads{instance=~'$instance.*'}[2m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(mysql_global_status_innodb_data_writes{instance=~'$instance.*'}[2m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{instance=~'$instance.*'}[1m])",
     "legendFormat": "Slow Queries on {{instance }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(mysql_global_status_commands_total{instance=~'$instance.*'}[5m]))",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$instance\", command=\"admin_commands\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"commit\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"delete\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"insert\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"insert_select\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"replace\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"rollback\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"select\"}[5m])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{ instance=~'$instance.*', command=\"update\"}[5m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "mysql  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads{instance=~'$instance.*'}[10m])",
     "legendFormat": "reads - {{ instance }}"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes{instance=~'$instance.*'}[10m])",
     "legendFormat": "write - {{ instance }}"
    }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{instance=~'$instance.*'}[5m])",
     "legendFormat": "received - {{ instance }}"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{instance=~'$instance.*'}[5m])",
     "legendFormat": "sent - {{ instance }}"
    }
   ]
  }
 ]
}