{
 "title": "Process Status",
 "description": "This dashboard is another version of Named processes dashboard",
 "tags": [ "process" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resident memory map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"resident\"} > 0) by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "cpu map",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval] ))  by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "proportional resident memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"resident\"} > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (rate(namedprocess_namegroup_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) )without (mode) > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory (average)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"resident\"} / ignoring(memtype) namedprocess_namegroup_num_procs > 0",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "num processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{instance=~\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{instance=~\"$instance\", memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "voluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$instance\", ctxswitchtype=\"voluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "nonvoluntary context switches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_context_switches_total{instance=~\"$instance\", ctxswitchtype=\"nonvoluntary\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "file descripters",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{instance=~\"$instance\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "major page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_major_page_faults_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "minor page faults",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_minor_page_faults_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "uptime(oldest)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (avg by (groupname) (namedprocess_namegroup_oldest_start_time_seconds{instance=~\"$instance\"} > 0))",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}