{
 "title": "Postfix Queues",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(postfix_queue_stat, instance)"
    }
   },
   {
    "name": "queue",
    "query": {
     "query": "label_values(postfix_queue_stat, queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queued messages $queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "queue",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postfix_queue_stat{instance=\"$instance\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queued messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "postfix_queue_stat{instance=\"$instance\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "postfix_queue_stat_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}