{
 "title": "Openldap",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(openldap_scrape, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Add,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Add"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Bind,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Bind"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Unbind,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Unbind"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Compare,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Compare"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Delete,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Delete"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Extended,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Extended"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Modify,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Modify"
    },
    {
     "expr": "rate(openldap_monitor_operation{instance=~'$instance', dn=\"cn=Search,cn=Operations,cn=Monitor\"}[2m])",
     "legendFormat": "Search"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Active,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Max Pending,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Max Pending"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Max,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Open,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Pending,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Starting,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Starting"
    },
    {
     "expr": "openldap_monitored_object{instance=~'$instance', dn=\"cn=Active,cn=Threads,cn=Monitor\"}",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openldap_monitor_counter_object{instance=~'$instance', dn=\"cn=Current,cn=Connections,cn=Monitor\"}[2m])",
     "legendFormat": "Current "
    },
    {
     "expr": "rate(openldap_monitor_counter_object{instance=~'$instance', dn=\"cn=Max File Descriptors,cn=Connections,cn=Monitor\"}[2m])",
     "legendFormat": "Max File Descriptors"
    },
    {
     "expr": "rate(openldap_monitor_counter_object{instance=~'$instance', dn=\"cn=Total,cn=Connections,cn=Monitor\"}[2m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "R/W Waiters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openldap_monitor_counter_object{instance=~'$instance', dn=\"cn=Read,cn=Waiters,cn=Monitor\"}[2m])",
     "legendFormat": "Read Waiters"
    },
    {
     "expr": "rate(openldap_monitor_counter_object{instance=~'$instance', dn=\"cn=Write,cn=Waiters,cn=Monitor\"}[2m])",
     "legendFormat": "Write Waiters"
    }
   ]
  }
 ]
}