{
 "title": "Mailbox Protocols Requests",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Average processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mailboxd_soap_ms_avg\n", "legendFormat": "Soap {{instance}}" },
    { "expr": "mailboxd_pop_ms_avg", "legendFormat": "Pop {{instance}}" },
    { "expr": "mailboxd_imap_ms_avg", "legendFormat": "Imap {{instance}}" }
   ]
  },
  {
   "title": "LMTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mailboxd_lmtp_conn", "legendFormat": "{{instance}}" },
    { "expr": "mailboxd_lmtp_rcvd_msgs", "legendFormat": "{{instance}}" },
    { "expr": "mailboxd_lmtp_dlvd_msgs", "legendFormat": "{{instance}}" },
    { "expr": "mailboxd_lmtp_rcvd_rcpt", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SOAP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_soap_sessions{job=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SOAP Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mailboxd_soap_count{job=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IMAP Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mailboxd_imap_count", "legendFormat": "Count {{instance}}" },
    { "expr": "mailboxd_imap_conn", "legendFormat": "IMAP Connections {{instance}}" },
    { "expr": "mailboxd_imap_ssl_conn", "legendFormat": "IMAPS Connections {{instance}}" }
   ]
  },
  {
   "title": "IMAP Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mailboxd_imap_threads", "legendFormat": "IMAP Threads {{instance}}" },
    { "expr": "mailboxd_imap_ssl_threads", "legendFormat": "IMAPS threads {{instance}}" }
   ]
  },
  {
   "title": "POP3 Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mailboxd_pop_count", "legendFormat": "Count {{instance}}" },
    { "expr": "mailboxd_pop_conn", "legendFormat": "POP3 connections {{instance}}" },
    { "expr": "mailboxd_pop_ssl_conn", "legendFormat": "POP3s connections {instance}" }
   ]
  },
  {
   "title": "POP3 Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "mailboxd_pop_threads", "legendFormat": "POP3 threads {{instance}}" },
    { "expr": "mailboxd_pop_ssl_threads", "legendFormat": "POP3s threads {{instance}}" }
   ]
  }
 ]
}